name: Docker Builds
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: use reposirory
        uses: actions/checkout@v3
      - name: use node
        run: npm ci
      - name: start
        run: npm run start
